driver:
  name: docker
  use_sudo: false
  privileged: true
  forward:
    - 80

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  local_salt_root: '.'
  is_file_root: true
  require_chef: false
  grains:
    kitchen: enabled
  state_top:
    base:
      "*":
        - users
        - sudoers
        - rsyslog
        - redis

transport:
  name: sftp # use kitchen-sync for transferring files

platforms:
  - name: ubuntu-18.04

suites:
  - name: oxygen
    provisioner:
      salt_bootstrap_options: -X -p git stable 2018.3
    includes: ubuntu-18.04
    verifier:
      name: shell
      remote_exec: false
      command: py.test -v tests/
