import requests
import string
import yaml


def fetch_ip_list() -> dict:
    """Fetches the Fastly IP list"""
    response = requests.get("https://api.fastly.com/public-ip-list")
    return response.json()


def update_salt_state(ip_list: dict) -> None:
    """Update firewall with IP addresses from Fastly API.

    Args:
        ip_list (dict): IP addresses from Fastly API.

    Returns:
        None: The result is written to file.
    """
    salt_state = {"firewall": {}}
    for index, ip in enumerate(ip_list["addresses"]):
        salt_state["firewall"][f"fastly_syslog_ipv4_{string.ascii_lowercase[index]}"] = {
            "source": ip,
            "port": 514,
        }

    for index, ip in enumerate(ip_list["ipv6_addresses"]):
        salt_state["firewall"][f"fastly_syslog_ipv6_{string.ascii_lowercase[index]}"] = {
            "source6": ip,
            "port": 514,
        }

    with open("pillar/base/firewall/fastly-logging.sls", "w") as file:
        file.write("# This file is automatically generated by .github/workflows/update_fastly_ips.yml\n")
        file.write("# IP addresses are fetched from https://api.fastly.com/public-ip-list\n\n")
        yaml.safe_dump(salt_state, file, default_flow_style=False)


if __name__ == "__main__":
    update_salt_state(fetch_ip_list())
